services:
  mongodb:
    image: mongo:5.0
    container_name: medisphere-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medisphere-network

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: medisphere-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/medisphere-realm.json:/opt/keycloak/data/import/medisphere-realm.json
    command: start-dev --http-port=9090 --import-realm
    ports:
      - "9090:9090"
    networks:
      - medisphere-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: medisphere-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - medisphere-network

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: medisphere-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - medisphere-network

volumes:
  mongodb_data:

networks:
  medisphere-network:
    driver: bridge
